### ISSUE TITLE
Using `UsePaperModernChatEvent` parse message as viewer despite the config set to sender

### ISSUE THREAD

**Issue by cupang-afk** [LOOHP/InteractiveChat#138]
i have `!pos` as custom placeholder which show player location (the sender location)

when i ask friend to give their location, i recieve my location instead
![image](https://user-images.githubusercontent.com/66926348/219653427-4f2e5a0c-ee65-413c-a191-3a0a642ba454.png)
in the screenshot, the first one is when `UsePaperModernChatEvent` set to `true`
and the second one is when it set to `false`

my config for `!pos`: 
```yaml
ParsePlayer: sender
  Keyword: (?i)(!pos)
  ParseKeyword: false
  Cooldown: 5
  Hover:
    Enable: false
    Text: []
  Click:
    Enable: false
    Action: ''
    Value: ''
  Replace:
    Enable: true
    ReplaceText: '&a%player_world_type% &f%player_x% %player_y% %player_z%'
  Name: '!pos'
  Description: '&eShows your current position!'
```
i also have DiscordSRV to bridge minecraft chat to discord, and interestingly, discordsrv send the correct postition
![image](https://user-images.githubusercontent.com/66926348/219653455-3faf96ec-7c50-4c1b-8053-76ba0ab13716.png)

my DiscordSRV config related to paper chat event were turned on 
```yaml
VentureChatBungee: true
EnablePresenceInformation: true
UseModernPaperChatEvent: true
```
i haven't tested with other placeholder yet
