### ISSUE TITLE
[BUG] Illegal characters in chat

### ISSUE THREAD

**Issue by ZorudaRinku** [LOOHP/InteractiveChat#2]
When clicking on a players name (with default config) It suggests "/msg player " but you type something and hit send and you get kicked. Backspacing you can see it actually says "/msg player7r7r "

**Comment by LOOHP** [comment]
Which Minecraft version are you running?

**Comment by LOOHP** [comment]
Also which plugin is your /msg using?

**Comment by ZorudaRinku** [comment]
git-paper-224 (1.15.2)
https://www.spigotmc.org/resources/chat-manager-1-7-1-15-with-30-features-and-40-commands.52245/

**Comment by LOOHP** [comment]
I can't seem to recreate the issue, can you send me your config? (despite you said it is the default, it is still worth taking a look.)

**Comment by ZorudaRinku** [comment]
Sure, I'm assuming at this point its a different plugin causing it like placeholderapi or something because the click command doesn't seem to look off...
```
Options:
  Updater: true
Messages:
  NoPermission: '&cYou do not have permission to use that command!'
  InvExpired: '&cThis inventory view has expired!'
  ReloadPlugin: '&aInteractive Chat has been reloaded!'
  LimitReached: '&cPlease do now use excessive amount of placeholders in one message!'
Settings:
  FilterUselessColorCodes: true
  CommandsToParse:
  - /emsg.*
  - /msg.*
  - /pm.*
  - /tell.*
  - /r.*
  UniversalCooldown: 0
  MaxPlaceholders: -1
  PlayerNotFound:
    Hover:
      Enable: true
      Text:
      - '&cUnable to parse placeholder..'
    Click:
      Enable: false
      Action: SUGGEST_COMMAND
      Value: ''
    Replace:
      Enable: true
      ReplaceText: '&c{Placeholer}&r'
Chat:
  AllowMention: true
  MentionedSound: ENTITY_EXPERIENCE_ORB_PICKUP
  MentionedTitle: ''
  MentionedTitleDuration: 1.5
  UnknownPlayerMentionSubtitle: '&fSomeone had mentioned you in the chat!'
  KnownPlayerMentionSubtitle: '&3%player_name% &fmentioned you in the chat!'
  MentionHighlight: '&e{MentionedPlayer}'
  MentionHoverText:
  - '&b{Sender} mentioned you!'
ItemDisplay:
  Item:
    Enabled: true
    CaseSensitive: false
    Keyword: '[item]'
    Aliases:
    - (?i)(\[i\])
    Text: '&f[&f{Item} &bx{Amount}&f]'
    InventoryTitle: '%player_name%''s Item'
    Cooldown: 0
    GUIEnabled: true
    Frame:
      Primary: MAGENTA_STAINED_GLASS_PANE
      Secondary: BLACK_STAINED_GLASS_PANE
  Inventory:
    Enabled: true
    CaseSensitive: false
    Keyword: '[inv]'
    Aliases:
    - (?i)(\[inventory\])
    Text: '&f[&b%player_name%''s Inventory&f]'
    InventoryTitle: '%player_name%''s Inventory'
    Cooldown: 0
    HoverMessage:
    - '&bClick to view!'
  EnderChest:
    Enabled: true
    CaseSensitive: false
    Keyword: '[ender]'
    Aliases:
    - (?i)(\[e\])
    Text: '&f[&d%player_name%''s Ender Chest&f]'
    InventoryTitle: '%player_name%''s Ender Chest'
    Cooldown: 0
    HoverMessage:
    - '&bClick to view!'
Player:
  UsePlayerNameInteraction: true
  CaseSensitive: true
  Hover:
    Enable: true
    Text:
    - '&aWorld: %player_world%'
  Click:
    Enable: true
    Action: SUGGEST_COMMAND
    Value: '/msg %player_name% '
CustomPlaceholders:
  '1':
    ParsePlayer: sender
    Text: '[money]'
    Aliases:
    - (?i)(\[m\])
    ParseKeyword: false
    CaseSensitive: true
    Cooldown: 0
    Hover:
      Enable: true
      Text:
      - '&6%player_name%''s Balance: $%vault_eco_balance_commas%'
    Click:
      Enable: true
      Action: SUGGEST_COMMAND
      Value: '/pay %player_name% '
    Replace:
      Enable: true
      ReplaceText: '[%player_name%''s Balance]'
  '2':
    ParsePlayer: viewer
    Text: SunKnights
    Aliases: []
    ParseKeyword: false
    CaseSensitive: false
    Cooldown: 0
    Hover:
      Enable: true
      Text:
      - '&eVisit the author''s server!'
      - '&bClick me!'
    Click:
      Enable: true
      Action: OPEN_URL
      Value: https://sunknights.fun
    Replace:
      Enable: true
      ReplaceText: '&6&lSun&e&lKnights'
  '3':
    ParsePlayer: sender
    Text: '[gametime]'
    Aliases: []
    ParseKeyword: false
    CaseSensitive: true
    Cooldown: 0
    Hover:
      Enable: false
      Text: []
    Click:
      Enable: false
      Action: ''
      Value: ''
    Replace:
      Enable: true
      ReplaceText: '%player_world_time_24%'
  '4':
    ParsePlayer: viewer
    Text: '[Hover]'
    Aliases: []
    ParseKeyword: false
    CaseSensitive: false
    Cooldown: 0
    Hover:
      Enable: true
      Text:
      - '&bHover Text is cool!'
    Click:
      Enable: false
      Action: ''
      Value: ''
    Replace:
      Enable: false
      ReplaceText: ''
  '5':
    ParsePlayer: viewer
    Text: discord
    Aliases: []
    ParseKeyword: false
    CaseSensitive: false
    Cooldown: 0
    Hover:
      Enable: true
      Text:
      - '&eJoin the discord!'
      - '&bClick me!'
    Click:
      Enable: true
      Action: OPEN_URL
      Value: https://discord.gg/9sCRjZx
    Replace:
      Enable: true
      ReplaceText: '&9&nDiscord&f'
```
