### ISSUE TITLE
Add a variable that parses out the text

### ISSUE THREAD

**Issue by SheerYin** [LOOHP/InteractiveChat#88]
I am trying to parse a url using regex
Then output [URL] Open website when clicked
This way the player sends a very long URL and automatically becomes a clickable [URL]
But I don't find a variable that parses out the text

我正在尝试使用正则表达式解析 网址
然后输出 [网址] 点击时打开网址
这样玩家发送一个很长的 网址 并自动变成一个可点击的 [网址]
但我没有找到解析文本的变量

  # (https?:\/\/(?:www\.|(?!www))[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\.[^\s]{2,}|www\.[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\.[^\s]{2,}|https?:\/\/(?:www\.|(?!www))[a-zA-Z0-9]\.[^\s]{2,}|www\.[a-zA-Z0-9]\.[^\s]{2,})
  # ((http|https|ftp|ftps)\:\/\/)?[a-zA-Z0-9\-]+\.[a-zA-Z]{2,3}(\/\S*)?
  # ((http|https|ftp|ftps)\:\/\/)?[a-zA-Z0-9\-]+\.[a-zA-Z]{2,3}(\/\S*)?([^\s]+)

from CMI

**Comment by LOOHP** [comment]
You mean something like this?
```yaml
  '4':
    ParsePlayer: viewer
    Keyword: "(https?://(?:www.|(?!www))[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9].[^\\s]{2,}|www.[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9].[^\\s]{2,}|https?://(?:www.|(?!www))[a-zA-Z0-9].[^\\s]{2,}|www.[a-zA-Z0-9].[^\\s]{2,})"
    ParseKeyword: false
    Cooldown: 0
    Hover:
      Enable: true
      Text:
        - "&eClick to open: &b$1"
    Click:
      Enable: true
      Action: OPEN_URL
      Value: "$1"
    Replace:
      Enable: true
      ReplaceText: "&b[&eURL&b]"
    Name: "[URL]"
    Description: "&eExample of using Regex matching groups to open URLs"
```
